import { Platform, StyleSheet } from 'react-native';
import { HomeTheme, Radius, Spacing } from '@/constants/theme';

export const FormSheetColors = {
  sheetBg: '#FFFFFF',
  overlay: 'rgba(0,0,0,0.5)',
  pageBg: '#F4F6F8',
  sectionBg: '#FFFFFF',
  sectionBorder: '#ECEEF2',
  label: '#6B7280',
  text: '#111827',
  placeholder: '#9CA3AF',
  inputBg: '#FFFFFF',
  inputBorder: '#D1D5DB',
  chipBg: '#F3F4F6',
  chipBorder: '#E5E7EB',
  divider: '#ECEEF2',
  handle: '#D1D5DB',
} as const;

export const formSheetStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: FormSheetColors.overlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: FormSheetColors.sheetBg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '94%',
    overflow: 'hidden',
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: FormSheetColors.handle,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  closeBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: FormSheetColors.pageBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
    backgroundColor: FormSheetColors.pageBg,
  },
  hero: {
    borderRadius: 20,
    padding: Spacing.lg,
    marginBottom: Spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    borderWidth: 1,
  },
  heroIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroText: {
    flex: 1,
    gap: 4,
  },
  section: {
    backgroundColor: FormSheetColors.sectionBg,
    borderRadius: 18,
    padding: Spacing.md,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: FormSheetColors.sectionBorder,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: { elevation: 1 },
    }),
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: FormSheetColors.divider,
  },
  sectionIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: Radius.full,
    backgroundColor: FormSheetColors.chipBg,
    borderWidth: 1.5,
    borderColor: FormSheetColors.chipBorder,
  },
  chipSelected: {
    borderWidth: 1.5,
  },
  textInput: {
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: Spacing.md,
    paddingVertical: Platform.OS === 'ios' ? 14 : 12,
    fontSize: 15,
    color: FormSheetColors.text,
    fontWeight: '500',
  },
  suffixInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: Spacing.md,
    minHeight: 50,
  },
  suffixInput: {
    flex: 1,
    fontSize: 15,
    color: FormSheetColors.text,
    fontWeight: '600',
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
  },
  pickerField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    minHeight: 50,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: Spacing.md,
    paddingVertical: 10,
    minHeight: 50,
  },
  twoColRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  halfCol: {
    flex: 1,
  },
  fieldGap: {
    marginBottom: Spacing.md,
  },
  notesInput: {
    minHeight: 96,
    textAlignVertical: 'top',
    paddingTop: Spacing.md,
  },
  footer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.md,
    backgroundColor: FormSheetColors.sheetBg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: FormSheetColors.divider,
  },
  saveBtn: {
    width: '100%',
    borderRadius: Radius.full,
    minHeight: 54,
  },
  saveBtnText: {
    fontSize: 16,
    fontWeight: '700',
  },
  historyRow: {
    backgroundColor: FormSheetColors.pageBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: FormSheetColors.sectionBorder,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    gap: 4,
  },
});
