import { Platform, StyleSheet } from 'react-native';
import { HomeTheme, Radius, Spacing } from '@/constants/theme';

export const FormSheetColors = {
  sheetBg: '#FFFFFF',
  overlay: 'rgba(0,0,0,0.5)',
  pageBg: '#F4F6F8',
  sectionBg: '#FFFFFF',
  sectionBorder: '#ECEEF2',
  label: '#6B7280',
  text: '#111827',
  placeholder: '#9CA3AF',
  inputBg: '#FFFFFF',
  inputBorder: '#D1D5DB',
  chipBg: '#F3F4F6',
  chipBorder: '#E5E7EB',
  divider: '#ECEEF2',
  handle: '#D1D5DB',
} as const;

export const formSheetStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: FormSheetColors.overlay,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: FormSheetColors.sheetBg,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '94%',
    overflow: 'hidden',
  },
  handle: {
    alignSelf: 'center',
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: FormSheetColors.handle,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: FormSheetColors.pageBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: {
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
    backgroundColor: FormSheetColors.pageBg,
  },
  hero: {
    borderRadius: 16,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
  },
  heroIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroText: {
    flex: 1,
    gap: 4,
  },
  section: {
    backgroundColor: FormSheetColors.sectionBg,
    borderRadius: 14,
    padding: Spacing.sm + 4,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: FormSheetColors.sectionBorder,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
      },
      android: { elevation: 1 },
    }),
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    paddingBottom: Spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: FormSheetColors.divider,
  },
  sectionIcon: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Radius.full,
    backgroundColor: FormSheetColors.chipBg,
    borderWidth: 1.5,
    borderColor: FormSheetColors.chipBorder,
  },
  chipSelected: {
    borderWidth: 1.5,
  },
  textInput: {
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 13,
    color: FormSheetColors.text,
    fontWeight: '500',
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      },
    }),
  },
  suffixInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: 10,
    minHeight: 36,
  },
  suffixInput: {
    flex: 1,
    fontSize: 13,
    color: FormSheetColors.text,
    fontWeight: '600',
    paddingVertical: 4,
    paddingHorizontal: 0,
    margin: 0,
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      },
    }),
  },
  pickerField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: 10,
    paddingVertical: 6,
    minHeight: 36,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: FormSheetColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: FormSheetColors.inputBorder,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minHeight: 36,
  },
  twoColRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  halfCol: {
    flex: 1,
  },
  fieldGap: {
    marginBottom: 8,
  },
  notesInput: {
    minHeight: 60,
    textAlignVertical: 'top',
    paddingTop: 6,
  },
  footer: {
    paddingHorizontal: Spacing.lg,
    paddingTop: Spacing.sm,
    backgroundColor: FormSheetColors.sheetBg,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: FormSheetColors.divider,
  },
  saveBtn: {
    width: '100%',
    borderRadius: Radius.full,
    minHeight: 46,
  },
  saveBtnText: {
    fontSize: 15,
    fontWeight: '700',
  },
  historyRow: {
    backgroundColor: FormSheetColors.pageBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: FormSheetColors.sectionBorder,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    gap: 4,
  },
  gradientHeader: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginBottom: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.md,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    flex: 1,
  },
  headerIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontSize: 18,
    lineHeight: 22,
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
