import React from 'react';
import { View, StyleSheet, Platform } from 'react-native';
import { HomeTheme, Radius, Spacing } from '@/constants/theme';
import { homeCardShadow } from '@/components/home/homeStyles';
import { ScheduleTheme } from './scheduleTheme';

export const ScheduleColors = {
  label: ScheduleTheme.textMuted,
  fieldText: ScheduleTheme.text,
  placeholder: ScheduleTheme.textMuted,
} as const;

export const scheduleFieldStyles = StyleSheet.create({
  sectionCard: {
    backgroundColor: ScheduleTheme.cardBg,
    borderRadius: 20,
    marginBottom: Spacing.md,
    overflow: 'hidden',
    ...homeCardShadow,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: 14,
    gap: Spacing.sm,
  },
  sectionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionBody: {
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.md,
  },
  entryCard: {
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  entryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  fieldLabel: {
    marginBottom: 6,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: 12,
    marginTop: Spacing.xs,
  },
  mealChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  mealChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.full,
    backgroundColor: ScheduleTheme.fieldBg,
    borderWidth: 1,
    borderColor: ScheduleTheme.fieldBorder,
  },
  mealChipActive: {
    borderWidth: 0,
  },
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    marginBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  timeRowIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeRowLabel: {
    flex: 1,
  },
  timeRowPicker: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: ScheduleTheme.cardBg,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 108,
    justifyContent: 'center',
  },
  compactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    marginBottom: Spacing.sm,
    gap: Spacing.sm,
  },
  compactRowBody: {
    flex: 1,
    gap: 2,
  },
  rowMenuBtn: {
    padding: 4,
  },
  fieldBlock: {
    marginBottom: Spacing.sm,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.full,
    backgroundColor: ScheduleTheme.fieldBg,
    borderWidth: 1,
    borderColor: ScheduleTheme.fieldBorder,
  },
  textInput: {
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    fontSize: 14,
    color: ScheduleTheme.text,
    marginBottom: Spacing.sm,
  },
  pickerField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    paddingVertical: 12,
    marginBottom: Spacing.sm,
    minHeight: 44,
  },
  twoColRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  halfCol: {
    flex: 1,
  },
  suffixInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingHorizontal: Spacing.md,
    marginBottom: Spacing.sm,
    minHeight: 44,
  },
  suffixInput: {
    flex: 1,
    fontSize: 14,
    color: ScheduleTheme.text,
    fontWeight: '600',
    paddingVertical: Platform.OS === 'ios' ? 10 : 8,
  },
  notifyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    paddingVertical: 12,
    marginBottom: Spacing.sm,
    minHeight: 44,
  },
  notesInput: {
    minHeight: 64,
    textAlignVertical: 'top',
    paddingTop: Spacing.sm,
  },
  expandedPanel: {
    backgroundColor: ScheduleTheme.fieldBg,
    borderRadius: 14,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: ScheduleTheme.fieldBorder,
    marginVertical: Spacing.sm,
  },
  dashedAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
    paddingVertical: 14,
    marginTop: Spacing.xs,
    borderRadius: 14,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: ScheduleTheme.dashedBorder,
    backgroundColor: HomeTheme.white,
  },
});
